
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (50,'CODESET',1);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (51,'CODESET_VALUE',1);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (53,'COMPETENCY',1);
Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (54,'ESSENTIAL_ELEMENT',1);

Insert into V2_SEQUENCER (SEQUENCER_ID,NAME,VALUE) values (60,'JOB',1);
